### ISSUE TITLE
When trying to use hover effect on dragover a cell every element gets the over class

### ISSUE THREAD

**Issue by demonmind** [cameronhimself/vue-drag-drop-demo#1]
I have a grid and each cell is a droppable container.

What i want to achieve is drag a div over a cell and while over the cell changes the background, like in the example shown.

Problem with that that all cells take that class over when i start dragging. 
How can i solve this situation.

**Comment by cameronhimself** [comment]
Closing this in favor of the [duplicate issue](https://github.com/cameronhimself/vue-drag-drop/issues/8) on the main vue-drag-drop repo.
